TMB Documentation: splinefun< Type > Class Template Reference
splinefun< Type > Class Template Reference
#include <splines.hpp>
Public Member Functions
splinefun ()
splinefun (const splinefun &fun)
splinefun (const vector< Type > &x_, const vector< Type > &y_, int method_=3)
void erase_data ()
~splinefun ()
void construct (const vector< Type > &x_, const vector< Type > &y_, int method_=3)
Type operator() (const Type &x_)
void natural_spline (int n, Type *x, Type *y, Type *b, Type *c, Type *d)
void fmm_spline (int n, Type *x, Type *y, Type *b, Type *c, Type *d)
void periodic_spline (int n, Type *x, Type *y, Type *b, Type *c, Type *d, Type *e)
void spline_coef (int *method, int *n, Type *x, Type *y, Type *b, Type *c, Type *d, Type *e)
void spline_eval (int *method, int *nu, Type *u, Type *v, int *n, Type *x, Type *y, Type *b, Type *c, Type *d)
Detailed Description
template<class Type>
class splinefun< Type >
Definition at line 48 of file splines.hpp.
Constructor & Destructor Documentation
template<class Type > splinefun< Type >::splinefun () inline
Definition at line 66 of file splines.hpp.
template<class Type > splinefun< Type >::splinefun (const splinefun< Type > & fun) inline
Definition at line 71 of file splines.hpp.
template<class Type > splinefun< Type >::splinefun (const vector< Type > & x_, const vector< Type > & y_, int method_ = 3) inline
Definition at line 90 of file splines.hpp.
template<class Type > splinefun< Type >::~splinefun () inline
Definition at line 103 of file splines.hpp.
Member Function Documentation
template<class Type > void splinefun< Type >::construct (const vector< Type > & x_, const vector< Type > & y_, int method_ = 3) inline
Definition at line 107 of file splines.hpp.
Referenced by splinefun< Type >::splinefun().
template<class Type > void splinefun< Type >::erase_data () inline
Definition at line 95 of file splines.hpp.
Referenced by splinefun< Type >::construct(), and splinefun< Type >::~splinefun().
template<class Type > void splinefun< Type >::fmm_spline (int n, Type * x, Type * y, Type * b, Type * c, Type * d) inline
Definition at line 233 of file splines.hpp.
Referenced by splinefun< Type >::spline_coef().
template<class Type > void splinefun< Type >::natural_spline (int n, Type * x, Type * y, Type * b, Type * c, Type * d) inline
Definition at line 155 of file splines.hpp.
Referenced by splinefun< Type >::spline_coef().
template<class Type > Type splinefun< Type >::operator() (const Type & x_) inline
Definition at line 127 of file splines.hpp.
template<class Type > void splinefun< Type >::periodic_spline (int n, Type * x, Type * y, Type * b, Type * c, Type * d, Type * e) inline
Definition at line 322 of file splines.hpp.
Referenced by splinefun< Type >::spline_coef().
template<class Type > void splinefun< Type >::spline_coef (int * method, int * n, Type * x, Type * y, Type * b, Type * c, Type * d, Type * e) inline
Definition at line 437 of file splines.hpp.
Referenced by splinefun< Type >::construct().
template<class Type > void splinefun< Type >::spline_eval (int * method, int * nu, Type * u, Type * v, int * n, Type * x, Type * y, Type * b, Type * c, Type * d) inline
Definition at line 452 of file splines.hpp.
Referenced by splinefun< Type >::operator()().
The documentation for this class was generated from the following file:
splines.hpp
License: GPL v2