TMB Documentation: objective_function< Type > Class Template Reference
objective_function< Type > Class Template Reference
Type definition of user-provided objective function (i.e. neg. log. like)
#include <tmb_core.hpp>
Public Member Functions
void pushParname (const char *x)
Called once for each occurance of PARAMETER_.
bool parallel_region ()
int count_parallel_regions ()
void set_parallel_region (int i)
objective_function (SEXP data_, SEXP parameters_, SEXP report_)
Constructor which among other things gives a value to "theta".
SEXP defaultpar ()
Extract theta vector from objetive function object.
SEXP parNames ()
Extract parnames vector from objetive function object.
double value (double x)
double value (AD< double > x)
double value (AD< AD< double > > x)
double value (AD< AD< AD< double > > > x)
int nparms (SEXP obj)
Find the length of theta, i.e. in application obj=parameters.
void fill (vector< Type > &x, const char *nam)
void fill (matrix< Type > &x, const char *nam)
template<class ArrayType >
void fill (ArrayType &x, const char *nam)
template<class ArrayType >
void fillmap (ArrayType &x, const char *nam)
SEXP getShape (const char *nam, RObjectTester expectedtype=NULL)
template<class ArrayType >
ArrayType fillShape (ArrayType x, const char *nam)
void fill (Type &x, char const *nam)
Type operator() ()
Type evalUserTemplate ()
Public Attributes
SEXP data
SEXP parameters
SEXP report
int index
vector< Type > theta
Consists of unlist(parameters_)
vector< const char * > thetanames
In R notation: names(theta). Contains repeated values.
report_stack< Type > reportvector
Used by "ADREPORT".
bool reversefill
vector< const char * > parnames
One name for each PARAMETER_ in user template.
bool parallel_ignore_statements
int current_parallel_region
int selected_parallel_region
int max_parallel_regions
Detailed Description
template<class Type>
class objective_function< Type >
Type definition of user-provided objective function (i.e. neg. log. like)
Definition at line 452 of file tmb_core.hpp.
Constructor & Destructor Documentation
template<class Type> objective_function< Type >::objective_function (SEXP data_, SEXP parameters_, SEXP report_) inline
Constructor which among other things gives a value to "theta".
Definition at line 529 of file tmb_core.hpp.
Member Function Documentation
template<class Type> int objective_function< Type >::count_parallel_regions () inline
Definition at line 503 of file tmb_core.hpp.
Referenced by MakeADFunObject(), and MakeADGradObject().
template<class Type> SEXP objective_function< Type >::defaultpar () inline
Extract theta vector from objetive function object.
Definition at line 555 of file tmb_core.hpp.
Referenced by MakeADFunObject(), and MakeADGradObject().
template<class Type> Type objective_function< Type >::evalUserTemplate () inline
Definition at line 677 of file tmb_core.hpp.
Referenced by MakeADFunObject(), MakeADGradObject(), and MakeADHessObject2().
template<class Type> void objective_function< Type >::fill (vector< Type > & x, const char * nam) inline
Definition at line 605 of file tmb_core.hpp.
template<class Type> void objective_function< Type >::fill (matrix< Type > & x, const char * nam) inline
Definition at line 613 of file tmb_core.hpp.
template<class Type> template<class ArrayType > void objective_function< Type >::fill (ArrayType & x, const char * nam) inline
Definition at line 624 of file tmb_core.hpp.
template<class Type> void objective_function< Type >::fill (Type & x, char const * nam) inline
Definition at line 668 of file tmb_core.hpp.
template<class Type> template<class ArrayType > void objective_function< Type >::fillmap (ArrayType & x, const char * nam) inline
Definition at line 635 of file tmb_core.hpp.
template<class Type> template<class ArrayType > ArrayType objective_function< Type >::fillShape (ArrayType x, const char * nam) inline
Definition at line 660 of file tmb_core.hpp.
template<class Type> SEXP objective_function< Type >::getShape (const char * nam, RObjectTester expectedtype = NULL) inline
Definition at line 650 of file tmb_core.hpp.
template<class Type> int objective_function< Type >::nparms (SEXP obj) inline
Find the length of theta, i.e. in application obj=parameters.
Definition at line 593 of file tmb_core.hpp.
template<class Type> Type objective_function< Type >::operator() ()
Examples:
ar1_4D.cpp, laplace.cpp, linreg.cpp, linreg_parallel.cpp, longlinreg.cpp, lr_test.cpp, matrix_arrays.cpp, multivariate_distributions.cpp, mvrw.cpp, mvrw_sparse.cpp, nan_error_ex.cpp, nmix.cpp, orange_big.cpp, sam.cpp, sde_linear.cpp, sdv_multi.cpp, sdv_multi_compact.cpp, socatt.cpp, spatial.cpp, spde.cpp, spde_aniso.cpp, thetalog.cpp, and transform.cpp.
template<class Type> bool objective_function< Type >::parallel_region () inline
Definition at line 494 of file tmb_core.hpp.
template<class Type> SEXP objective_function< Type >::parNames () inline
Extract parnames vector from objetive function object.
Definition at line 573 of file tmb_core.hpp.
Referenced by getParameterOrder().
template<class Type> void objective_function< Type >::pushParname (const char * x) inline
Called once for each occurance of PARAMETER_.
Definition at line 468 of file tmb_core.hpp.
template<class Type> void objective_function< Type >::set_parallel_region (int i) inline
Definition at line 512 of file tmb_core.hpp.
Referenced by MakeADFunObject(), MakeADGradObject(), and MakeADHessObject2().
template<class Type> double objective_function< Type >::value (double x) inline
Definition at line 587 of file tmb_core.hpp.
template<class Type> double objective_function< Type >::value (AD< double > x) inline
Definition at line 588 of file tmb_core.hpp.
template<class Type> double objective_function< Type >::value (AD< AD< double > > x) inline
Definition at line 589 of file tmb_core.hpp.
template<class Type> double objective_function< Type >::value (AD< AD< AD< double > > > x) inline
Definition at line 590 of file tmb_core.hpp.
Member Data Documentation
template<class Type> int objective_function< Type >::current_parallel_region
Definition at line 489 of file tmb_core.hpp.
template<class Type> SEXP objective_function< Type >::data
Definition at line 456 of file tmb_core.hpp.
template<class Type> int objective_function< Type >::index
Definition at line 460 of file tmb_core.hpp.
Referenced by EvalDoubleFunObject().
template<class Type> int objective_function< Type >::max_parallel_regions
Definition at line 491 of file tmb_core.hpp.
Referenced by parallel_accumulator< Type >::parallel_accumulator().
template<class Type> bool objective_function< Type >::parallel_ignore_statements
Definition at line 488 of file tmb_core.hpp.
template<class Type> SEXP objective_function< Type >::parameters
Definition at line 457 of file tmb_core.hpp.
template<class Type> vector<const char*> objective_function< Type >::parnames
One name for each PARAMETER_ in user template.
Definition at line 465 of file tmb_core.hpp.
Referenced by EvalDoubleFunObject().
template<class Type> SEXP objective_function< Type >::report
Definition at line 458 of file tmb_core.hpp.
template<class Type> report_stack<Type> objective_function< Type >::reportvector
Used by "ADREPORT".
Definition at line 463 of file tmb_core.hpp.
Referenced by EvalDoubleFunObject(), and MakeADFunObject().
template<class Type> bool objective_function< Type >::reversefill
Definition at line 464 of file tmb_core.hpp.
template<class Type> int objective_function< Type >::selected_parallel_region
Definition at line 490 of file tmb_core.hpp.
template<class Type> vector<Type> objective_function< Type >::theta
Consists of unlist(parameters_)
Definition at line 461 of file tmb_core.hpp.
Referenced by EvalDoubleFunObject(), MakeADFunObject(), MakeADGradObject(), and MakeADHessObject2().
template<class Type> vector<const char*> objective_function< Type >::thetanames
In R notation: names(theta). Contains repeated values.
Definition at line 462 of file tmb_core.hpp.
The documentation for this class was generated from the following file:
tmb_core.hpp
License: GPL v2