TMB Documentation: contAR2_t< scalartype_ > Class Template Reference
contAR2_t< scalartype_ > Class Template Reference
Continuous AR(2) process.
#include <density.hpp>
Public Member Functions
contAR2_t ()
contAR2_t (vectortype grid_, scalartype shape_, scalartype scale_=1)
matrix4x4 expB (scalartype t)
matrix2x2 V (scalartype t)
scalartype operator() (vectortype x, vectortype dx)
Evaluate the negative log density of the process x with nuisance parameters dx.
scalartype operator() (vectortype x)
arraytype matmult (matrix2x2 Q, arraytype x)
arraytype jacobian (arraytype x)
int ndim ()
Public Attributes
VARIANCE_NOT_YET_IMPLEMENTED
Detailed Description
template<class scalartype_>
class contAR2_t< scalartype_ >
Continuous AR(2) process.
Process with covariance satisfying the 2nd order ode
rho''=c1*rho'-rho on an arbitrary irregular grid.
(shape=c1/2, -1<shape<1). Initial condition rho(0)=1, rho'(0)=0,
rho''(0)=-1.
Process is augmented with derivatives in order to obtain exact sparseness of the full precision. That is, if a model is desired on a grid of size n, then additional n extra nuisance parameters must be supplied.
Parameters
grid_ Possibly irregular grid of length n
shape_ Parameter defining the shape of the correlation function.
scale_ Parameter defining the correlation range.
Definition at line 504 of file density.hpp.
Constructor & Destructor Documentation
template<class scalartype_> contAR2_t< scalartype_ >::contAR2_t () inline
Definition at line 520 of file density.hpp.
template<class scalartype_> contAR2_t< scalartype_ >::contAR2_t (vectortype grid_, scalartype shape_, scalartype scale_ = 1) inline
Definition at line 521 of file density.hpp.
Member Function Documentation
template<class scalartype_> matrix4x4 contAR2_t< scalartype_ >::expB (scalartype t) inline
Definition at line 543 of file density.hpp.
Referenced by contAR2_t< scalartype_ >::V().
template<class scalartype_> arraytype contAR2_t< scalartype_ >::jacobian (arraytype x) inline
Definition at line 585 of file density.hpp.
template<class scalartype_> arraytype contAR2_t< scalartype_ >::matmult (matrix2x2 Q, arraytype x) inline
Definition at line 579 of file density.hpp.
Referenced by contAR2_t< scalartype_ >::jacobian().
template<class scalartype_> int contAR2_t< scalartype_ >::ndim () inline
Definition at line 602 of file density.hpp.
template<class scalartype_> scalartype contAR2_t< scalartype_ >::operator() (vectortype x, vectortype dx) inline
Evaluate the negative log density of the process x with nuisance parameters dx.
Definition at line 556 of file density.hpp.
Referenced by contAR2_t< scalartype_ >::operator()().
template<class scalartype_> scalartype contAR2_t< scalartype_ >::operator() (vectortype x) inline
Definition at line 572 of file density.hpp.
template<class scalartype_> matrix2x2 contAR2_t< scalartype_ >::V (scalartype t) inline
Definition at line 547 of file density.hpp.
Referenced by contAR2_t< scalartype_ >::contAR2_t().
Member Data Documentation
template<class scalartype_> contAR2_t< scalartype_ >::VARIANCE_NOT_YET_IMPLEMENTED
Definition at line 603 of file density.hpp.
The documentation for this class was generated from the following file:
density.hpp
License: GPL v2