TMB Documentation: convert.hpp File Reference
convert.hpp File Reference
Convert vector/matrix-Types to double SEXP types.
Macros
#define asSEXP_VECTOR_OF_NUMERIC(Type)
Functions
double asDouble (int x)
double asDouble (double x)
double asDouble (AD< double > x)
double asDouble (AD< AD< double > > x)
double asDouble (AD< AD< AD< double > > > x)
template<class Type >
SEXP asSEXP (const matrix< Type > &a)
Convert TMB matrix, vector, scalar or int to R style.
asSEXP_VECTOR_OF_NUMERIC (int) asSEXP_VECTOR_OF_NUMERIC(double) template< class Type > asSEXP_VECTOR_OF_NUMERIC(AD< Type >) template< class Type > SEXP asSEXP(const vector< Type > &a)
SEXP asSEXP (const double &a)
SEXP asSEXP (const int &a)
template<class Type >
SEXP asSEXP (const AD< Type > &a)
template<class Type >
vector< Type > asVector (SEXP x)
Construct c++-vector from SEXP object.
template<class Type >
matrix< Type > asMatrix (const vector< Type > &x, int nr, int nc)
Vector <-> Matrix conversion (for row-major matrices)
template<class Type >
matrix< Type > asMatrix (SEXP x)
Construct c++-matrix from SEXP object.
template<class Type >
vector< Type > asVector (matrix< Type > x)
template<class Type >
SEXP asSEXP (const tmbutils::array< Type > &a)
template<class Type >
SEXP asSEXP (Eigen::SparseMatrix< Type > x)
Detailed Description
Convert vector/matrix-Types to double SEXP types.
Definition in file convert.hpp.
Macro Definition Documentation
#define asSEXP_VECTOR_OF_NUMERIC (Type)
Value:
SEXP asSEXP(const vector<Type> &a)                      \
{                                                       \
  int size = a.size();                                  \
  SEXP val;                                             \
  PROTECT(val = allocVector(REALSXP,size));             \
  double *p = REAL(val);                                \
  for (int i = 0; i < size; i++) p[i] = asDouble(a[i]); \
  UNPROTECT(1);                                         \
  return val;                                           \
}
Definition at line 36 of file convert.hpp.
Function Documentation
double asDouble (int x)
Definition at line 8 of file convert.hpp.
Referenced by asSEXP().
double asDouble (double x)
Definition at line 9 of file convert.hpp.
double asDouble (AD< double > x)
Definition at line 10 of file convert.hpp.
double asDouble (AD< AD< double > > x)
Definition at line 11 of file convert.hpp.
double asDouble (AD< AD< AD< double > > > x)
Definition at line 12 of file convert.hpp.
template<class Type > matrix<Type> asMatrix (const vector< Type > & x, int nr, int nc)
Vector <-> Matrix conversion (for row-major matrices)
Definition at line 99 of file convert.hpp.
Referenced by EvalADFunObjectTemplate(), HessianSparsityPattern(), autodiff::hessian_t< Functor, Type >::operator()(), and autodiff::jacobian_t< Functor, Type >::operator()().
template<class Type > matrix<Type> asMatrix (SEXP x)
Construct c++-matrix from SEXP object.
Definition at line 112 of file convert.hpp.
template<class Type > SEXP asSEXP (const matrix< Type > & a)
Convert TMB matrix, vector, scalar or int to R style.
Definition at line 16 of file convert.hpp.
Referenced by asSEXP(), asSEXP_VECTOR_OF_NUMERIC(), and config_struct::set().
SEXP asSEXP (const double & a)
Definition at line 64 of file convert.hpp.
SEXP asSEXP (const int & a)
Definition at line 72 of file convert.hpp.
template<class Type > SEXP asSEXP (const AD< Type > & a)
Definition at line 82 of file convert.hpp.
template<class Type > SEXP asSEXP (const tmbutils::array< Type > & a)
Definition at line 138 of file convert.hpp.
template<class Type > SEXP asSEXP (Eigen::SparseMatrix< Type > x)
Create R-triplet sparse matrix from Eigen sparse matrix
Definition at line 154 of file convert.hpp.
asSEXP_VECTOR_OF_NUMERIC (int) const
Definition at line 47 of file convert.hpp.
template<class Type > vector<Type> asVector (SEXP x)
Construct c++-vector from SEXP object.
Definition at line 88 of file convert.hpp.
template<class Type > vector<Type> asVector (matrix< Type > x)
Definition at line 126 of file convert.hpp.
License: GPL v2