TMB Documentation: lgamma.hpp File Reference
lgamma.hpp File Reference
Gamma function and gamma probability densities.
Functions
template<class Type >
Type lgamma (Type x)
Logarithm of gamma function (following R argument convention).
template<class Type >
Type lgamma_approx (const Type &y)
template<class Type >
Type dnbinom (const Type &x, const Type &size, const Type &prob, int give_log=0)
Negative binomial probability function.Parameterized through size and prob parameters, following R-convention.
template<class Type >
Type dnbinom2 (const Type &x, const Type &mu, const Type &var, int give_log=0)
Negative binomial probability function.Alternative parameterization through mean and variance parameters.
template<class Type >
Type dpois (const Type &x, const Type &lambda, int give_log=0)
Poisson probability function.
template<class Type >
Type dgamma (Type y, Type shape, Type scale, int give_log=0)
Density of X where X~gamma distributed.
template<class Type >
Type dlgamma (Type y, Type shape, Type scale, int give_log=0)
Density of log(X) where X~gamma distributed.
template<class Type >
Type dzipois (const Type &x, const Type &lambda, const Type &zip, int give_log=0)
Zero-Inflated Poisson probability function.
template<class Type >
Type dzinbinom (const Type &x, const Type &size, const Type &p, const Type &zip, int give_log=0)
Zero-Inflated negative binomial probability function.
template<class Type >
Type dzinbinom2 (const Type &x, const Type &mu, const Type &var, const Type &zip, int give_log=0)
Zero-Inflated negative binomial probability function.
Detailed Description
Gamma function and gamma probability densities.
Definition in file lgamma.hpp.
Function Documentation
template<class Type > Type lgamma (Type x)
Logarithm of gamma function (following R argument convention).
Examples:
nmix.cpp.
Definition at line 11 of file lgamma.hpp.
Referenced by dbeta(), dbinom(), df(), dgamma(), dlgamma(), dmultinom(), dnbinom(), dpois(), dt(), matern(), pgamma(), and qgamma().
template<class Type > Type lgamma_approx (const Type & y) inline
Definition at line 21 of file lgamma.hpp.
License: GPL v2