TMB Documentation: atomic Namespace Reference
atomic Namespace Reference
Namespace with special functions and derivatives.
Namespaces
Rmath
Namespace with double versions of R special math library.
Classes
struct forrev_derivatives
General class to construct 'double versions' of the generalized symbol.
struct Block
struct Triangle
struct nestedTriangle
Representation of 'block-binomial' matrix.
struct nestedTriangle< 0 >
Functions
template<class matrix_pade >
matrix_pade expm (matrix_pade A)
matrix< double > expm (vector< matrix< double > > args)
template<class Type >
CppAD::vector< Type > args2vector (vector< matrix< Type > > args, int skip=-1)
Interface to atomic functions.
template<class Type >
matrix< Type > vec2mat (CppAD::vector< Type > x, int m, int n, int offset=0)
Convert segment of CppAD::vector to Eigen::Matrix.
template<class Type >
CppAD::vector< Type > mat2vec (matrix< Type > x)
Convert Eigen::Matrix to CppAD::vector by stacking the matrix columns.
template<class Type >
matrix< Type > matmul (matrix< Type > x, matrix< Type > y)
Matrix multiply.
template<class Type >
matrix< Type > matinv (matrix< Type > x)
template<class Type >
matrix< Type > matinvpd (matrix< Type > x, Type &logdet)
template<class Type >
Type logdet (matrix< Type > x)
template<class Type >
Type nldmvnorm (vector< Type > x, matrix< Type > Sigma)
template<class Type >
matrix< Type > expm (matrix< Type > x)
Matrix exponential.
User defined atomic functions
Note
The following procedure is automatically performed with the macro REGISTER_ATOMIC.
    Given function f0. Define recursively higher order reverse
    mode derivatives:
    f0: R^(n)         ->  R^(m)     (  x           -> f0 (x)    )
    f1: R^(n+m)       ->  R^(n)     ( (x,w1)       -> f0'(x)*w1 )
    f2: R^(n+m+n)     ->  R^(n+m)   ( (x,w1,w2)    -> f1'(x)*w2 )
    f3: R^(n+m+n+n+m) ->  R^(n+m+n) ( (x,w1,w2,w3) -> f2'(x)*w3 )
    1. We define a 'generalized symbol' to represent all of these.
    _Reverse_mode_AD_ is trivially obtained for this symbol by calling
    itself on a higher level. Each occurance on the tape will occupy
    O(n+m) memory units independent of the number of flops performed
    by f0.
    2. _Double_versions_ of the generalized symbol are obtained using
    nested AD types to tape f0, then recursively tape forward and
    reverse mode sweeps.
    Finally, given (1) and (2) the macro TMB_ATOMIC_VECTOR_FUNCTION
    will generate the atomic symbol.
template<class Base , class Func >
CppAD::ADFun< Base > * generate_tape (Func f, vector< double > x_)
Construct a tape of a given template functor (Will be used to tape 'f0' for different nested AD types)
template<class Base >
CppAD::ADFun< Base > * forrev (CppAD::ADFun< AD< Base > > *padf, vector< double > x_)
Lift tape of fn up one level by taping forward and reverse sweeps. Note: x_ needs only have length equal to the input domain dimension of f0. Zeros are filled in for all range directions.
template<class ADBase >
CppAD::ADFun< double > * multi_forrev (CppAD::ADFun< ADBase > *padf, vector< double > x_)
Recursively apply forrev until the lowest Base level (double)
template<>
CppAD::ADFun< double > * multi_forrev< double > (CppAD::ADFun< double > *padf, vector< double > x_)
template<class Func >
CppAD::ADFun< double > * tape_symbol (Func f, vector< double > x)
Tape symbol up to any order.
Variables
bool atomicFunctionGenerated = false
Atomic functions.
typedef Eigen::LDLT
< Eigen::Matrix< double,
Eigen::Dynamic, Eigen::Dynamic > > LDLT_t
template<class Type >
Type dnorm1 (Type x)
Standard normal density function 'dnorm1'. Needed to define derivative of 'pnorm1'.
template<class Type >
CppAD::vector< Type > pnorm1 (CppAD::vector< Type > x)
Atomic version of standard normal distribution function. Derivative is known to be 'dnorm1'.
template<class Type >
CppAD::vector< Type > qnorm1 (CppAD::vector< Type > x)
Atomic version of standard normal quantile function. Derivative is expressed through 'dnorm1'.
template<class Type >
CppAD::vector< Type > D_incpl_gamma_shape (CppAD::vector< Type > x)
Atomic version of scaled incomplete gamma function differentiated to any order wrt. shape parameter
where the 4 input parameters are passed as a vector . Note that the normalized incomplete gamma function is obtained as the special case and . Valid parameter range: .
template<class Type >
CppAD::vector< Type > inv_incpl_gamma (CppAD::vector< Type > x)
Atomic version of inverse of scaled incomplete gamma function. Given find such that
where the 3 input parameters are passed as a vector . The special case gives the inverse normalized incomplete gamma function. Valid parameter range: .
template<class Type >
CppAD::vector< Type > D_lgamma (CppAD::vector< Type > x)
Atomic version of the n'th order derivative of the log gamma function.
where the 2 input parameters are passed as a vector . The special case gives the log gamma function.
template<class Type >
CppAD::vector< Type > ppois (CppAD::vector< Type > x)
Atomic version of poisson cdf . Valid parameter range: .
template<class Type >
CppAD::vector< Type > besselK (CppAD::vector< Type > x)
Atomic version of . Valid parameter range: .
template<class Type >
CppAD::vector< Type > matmul (CppAD::vector< Type > x)
Atomic version of matrix multiply. Multiplies n1-by-n2 matrix with n2-by-n3 matrix.
template<class Type >
CppAD::vector< Type > matinv (CppAD::vector< Type > x)
Atomic version of matrix inversion. Inverts n-by-n matrix by LU-decomposition.
template<class Type >
CppAD::vector< Type > logdet (CppAD::vector< Type > x)
Atomic version of log determinant of positive definite n-by-n matrix.
template<class Type >
CppAD::vector< Type > invpd (CppAD::vector< Type > x)
Atomic version of log determinant and inverse of positive definite n-by-n matrix. Calculated by Cholesky decomposition.
template<class Type >
CppAD::vector< Type > expm (CppAD::vector< Type > x)
Atomic version of generalized matrix exponential (closed under reverse mode differentiation).
Detailed Description
Namespace with special functions and derivatives.
This namespace extends the 'derivatives table' of CppAD.
R's special math library is extended with derivatives in cases where symbolic derivatives are available. These special functions are often iterative and therefore difficult to implement with AD types. Instead, we code the derivatives based on the double versions available from R. This approach requires fewer code lines, and has the benefit of obtaining the same high accuracy as R's math functions.
Some matrix operations are extended with derivatives. This greatly reduces the AD memory usage. Furthermore, these atomic operations can be linked to a performance library by setting preprocesor flag EIGEN_USE_BLAS.
New symbols can be added by advanced users. First option is to code the reverse mode derivatives by hand using the TMB_ATOMIC_VECTOR_FUNCTION macro, see source code for examples. Second option is to generate reverse mode derivatives automatically using the macro REGISTER_ATOMIC.
Typedef Documentation
typedef Eigen::LDLT<Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> > atomic::LDLT_t
Definition at line 440 of file atomic_math.hpp.
Function Documentation
template<class Type > CppAD::vector<Type> atomic::args2vector (vector< matrix< Type > > args, int skip = -1)
Definition at line 207 of file expm.hpp.
Referenced by expm().
template<class Type > CppAD::vector<Type> atomic::besselK (CppAD::vector< Type > x)
Atomic version of . Valid parameter range: .
Note
Derivative wrt. is currently not implemented.
Parameters
x Input vector of length 2.
Returns
Vector of length 1.
Referenced by besselK().
template<class Type > CppAD::vector<Type> atomic::D_incpl_gamma_shape (CppAD::vector< Type > x)
Atomic version of scaled incomplete gamma function differentiated to any order wrt. shape parameter
where the 4 input parameters are passed as a vector . Note that the normalized incomplete gamma function is obtained as the special case and . Valid parameter range: .
Warning
No check is performed on parameters
Parameters
x Input vector of length 4.
Returns
Vector of length 1.
Referenced by pgamma().
template<class Type > CppAD::vector<Type> atomic::D_lgamma (CppAD::vector< Type > x)
Atomic version of the n'th order derivative of the log gamma function.
where the 2 input parameters are passed as a vector . The special case gives the log gamma function.
Parameters
x Input vector of length 2.
Returns
Vector of length 1.
Referenced by lgamma().
template<class Type > Type atomic::dnorm1 (Type x)
Standard normal density function 'dnorm1'. Needed to define derivative of 'pnorm1'.
Definition at line 157 of file atomic_math.hpp.
template<class matrix_pade > matrix_pade atomic::expm (matrix_pade A)
Definition at line 159 of file expm.hpp.
Referenced by expm().
matrix<double> atomic::expm (vector< matrix< double > > args)
template<class Type > CppAD::vector<Type> atomic::expm (CppAD::vector< Type > x)
Atomic version of generalized matrix exponential (closed under reverse mode differentiation).
   Generalized matrix exponential:
   C(x1,x2,...,xn)
   Example: n=3
   [ C(x1)       ]        [ x1          ]   [ I ]
   [ C(x1,x2)    ] = expm [ x2 x1       ] * [ 0 ]
   [ C(x1,x3)    ]        [ x3    x1    ]   [ 0 ]
   [ C(x1,x2,x3) ]        [    x3 x2 x1 ]   [ 0 ]
   d/dx1 ( sum( C(x1,x2,x3) * x4 ) ) = C(x1^T, x2^T, x3^T, x4)
   d/dx2 ( sum( C(x1,x2,x3) * x4 ) ) = C(x1^T,       x3^T, x4)
   d/dx3 ( sum( C(x1,x2,x3) * x4 ) ) = C(x1^T, x2^T,       x4)
template<class Type > matrix<Type> atomic::expm (matrix< Type > x)
Matrix exponential.
Definition at line 295 of file expm.hpp.
template<class Base > CppAD::ADFun<Base>* atomic::forrev (CppAD::ADFun< AD< Base > > * padf, vector< double > x_)
Lift tape of fn up one level by taping forward and reverse sweeps. Note: x_ needs only have length equal to the input domain dimension of f0. Zeros are filled in for all range directions.
Definition at line 78 of file checkpoint_macro.hpp.
Referenced by multi_forrev().
template<class Base , class Func > CppAD::ADFun<Base>* atomic::generate_tape (Func f, vector< double > x_)
Construct a tape of a given template functor (Will be used to tape 'f0' for different nested AD types)
Definition at line 61 of file checkpoint_macro.hpp.
template<class Type > CppAD::vector<Type> atomic::inv_incpl_gamma (CppAD::vector< Type > x)
Atomic version of inverse of scaled incomplete gamma function. Given find such that
where the 3 input parameters are passed as a vector . The special case gives the inverse normalized incomplete gamma function. Valid parameter range: .
Warning
No check is performed on parameters
Parameters
x Input vector of length 3.
Returns
Vector of length 1.
Referenced by qgamma().
template<class Type > CppAD::vector<Type> atomic::invpd (CppAD::vector< Type > x)
Atomic version of log determinant and inverse of positive definite n-by-n matrix. Calculated by Cholesky decomposition.
Parameters
x Input vector of length n*n.
Returns
Vector of length 1+n*n.
Referenced by matinvpd().
template<class Type > CppAD::vector<Type> atomic::logdet (CppAD::vector< Type > x)
Atomic version of log determinant of positive definite n-by-n matrix.
Parameters
x Input vector of length n*n.
Returns
Vector of length 1.
Examples:
laplace.cpp.
Referenced by logdet(), and nldmvnorm().
template<class Type > Type atomic::logdet (matrix< Type > x)
Definition at line 514 of file atomic_math.hpp.
template<class Type > CppAD::vector<Type> atomic::mat2vec (matrix< Type > x)
Convert Eigen::Matrix to CppAD::vector by stacking the matrix columns.
Parameters
x Input matrix.
Definition at line 139 of file atomic_math.hpp.
Referenced by logdet(), matinv(), and matinvpd().
template<class Type > CppAD::vector<Type> atomic::matinv (CppAD::vector< Type > x)
Atomic version of matrix inversion. Inverts n-by-n matrix by LU-decomposition.
Parameters
x Input vector of length n*n.
Returns
Vector of length n*n.
Examples:
laplace.cpp.
Referenced by matinv(), and nldmvnorm().
template<class Type > matrix<Type> atomic::matinv (matrix< Type > x)
Definition at line 500 of file atomic_math.hpp.
template<class Type > matrix<Type> atomic::matinvpd (matrix< Type > x, Type & logdet)
Definition at line 506 of file atomic_math.hpp.
Referenced by MVNORM_t< scalartype_ >::setSigma().
template<class Type > CppAD::vector<Type> atomic::matmul (CppAD::vector< Type > x)
Atomic version of matrix multiply. Multiplies n1-by-n2 matrix with n2-by-n3 matrix.
Parameters
x Input vector of length 2+n1*n2+n2*n3 containing the output dimension (length=2), the first matrix (length=n1*n2) and the second matrix (length=n2*n3).
Returns
Vector of length n1*n3 containing result of matrix multiplication.
Referenced by matmul().
template<class Type > matrix<Type> atomic::matmul (matrix< Type > x, matrix< Type > y)
Matrix multiply.
Definition at line 491 of file atomic_math.hpp.
template<class ADBase > CppAD::ADFun<double>* atomic::multi_forrev (CppAD::ADFun< ADBase > * padf, vector< double > x_)
Recursively apply forrev until the lowest Base level (double)
Definition at line 98 of file checkpoint_macro.hpp.
Referenced by tape_symbol().
template<> CppAD::ADFun<double>* atomic::multi_forrev< double > (CppAD::ADFun< double > * padf, vector< double > x_)
Definition at line 102 of file checkpoint_macro.hpp.
template<class Type > Type atomic::nldmvnorm (vector< Type > x, matrix< Type > Sigma)
Definition at line 522 of file atomic_math.hpp.
template<class Type > CppAD::vector<Type> atomic::pnorm1 (CppAD::vector< Type > x)
Atomic version of standard normal distribution function. Derivative is known to be 'dnorm1'.
Parameters
x Input vector of length 1.
Returns
Vector of length 1.
Referenced by pnorm().
template<class Type > CppAD::vector<Type> atomic::ppois (CppAD::vector< Type > x)
Atomic version of poisson cdf . Valid parameter range: .
Warning
No check is performed on parameters
Parameters
x Input vector of length 2.
Returns
Vector of length 1.
Referenced by ppois().
template<class Type > CppAD::vector<Type> atomic::qnorm1 (CppAD::vector< Type > x)
Atomic version of standard normal quantile function. Derivative is expressed through 'dnorm1'.
Parameters
x Input vector of length 1.
Returns
Vector of length 1.
Referenced by qnorm().
template<class Func > CppAD::ADFun<double>* atomic::tape_symbol (Func f, vector< double > x)
Tape symbol up to any order.
Definition at line 107 of file checkpoint_macro.hpp.
Referenced by atomic::forrev_derivatives< UserFunctor >::do_init().
template<class Type > matrix<Type> atomic::vec2mat (CppAD::vector< Type > x, int m, int n, int offset = 0)
Convert segment of CppAD::vector to Eigen::Matrix.
Parameters
x Input vector.
m Number of rows in result.
n Number of columns in result.
offset Segment offset.
Definition at line 129 of file atomic_math.hpp.
Referenced by expm(), matinv(), matinvpd(), and matmul().
Variable Documentation
bool atomic::atomicFunctionGenerated = false
Definition at line 14 of file atomic_math.hpp.
Referenced by usingAtomics().
License: GPL v2