TMB Documentation: atomic::Rmath Namespace Reference
atomic::Rmath Namespace Reference
Namespace with double versions of some R special math functions.
Functions
double Rf_pnorm5 (double, double, double, int, int)
double Rf_qnorm5 (double, double, double, int, int)
double Rf_ppois (double, double, int, int)
double Rf_bessel_k (double, double, double)
double Rf_pgamma (double, double, double, int, int)
double Rf_qgamma (double, double, double, int, int)
double Rf_lgammafn (double)
double Rf_psigamma (double, double)
double Rf_fmin2 (double, double)
void integrand_D_incpl_gamma_shape (double *x, int nx, void *ex)
double D_incpl_gamma_shape (double x, double shape, double n, double logc)
double inv_incpl_gamma (double y, double shape, double logc)
double D_lgamma (double x, double n)
Detailed Description
Namespace with double versions of some R special math functions.
Function Documentation
double atomic::Rmath::D_incpl_gamma_shape (double x, double shape, double n, double logc)
Definition at line 76 of file atomic_math.hpp.
double atomic::Rmath::D_lgamma (double x, double n)
Definition at line 134 of file atomic_math.hpp.
void atomic::Rmath::integrand_D_incpl_gamma_shape (double * x, int nx, void * ex)
Definition at line 66 of file atomic_math.hpp.
double atomic::Rmath::inv_incpl_gamma (double y, double shape, double logc)
Definition at line 128 of file atomic_math.hpp.
double atomic::Rmath::Rf_bessel_k (double , double , double)
double atomic::Rmath::Rf_fmin2 (double , double)
Referenced by D_incpl_gamma_shape().
double atomic::Rmath::Rf_lgammafn (double)
Referenced by D_incpl_gamma_shape(), D_lgamma(), and inv_incpl_gamma().
double atomic::Rmath::Rf_pgamma (double , double , double , int , int)
Referenced by D_incpl_gamma_shape().
double atomic::Rmath::Rf_pnorm5 (double , double , double , int , int)
double atomic::Rmath::Rf_ppois (double , double , int , int)
double atomic::Rmath::Rf_psigamma (double , double)
Referenced by D_lgamma().
double atomic::Rmath::Rf_qgamma (double , double , double , int , int)
Referenced by inv_incpl_gamma().
double atomic::Rmath::Rf_qnorm5 (double , double , double , int , int)
License: GPL v2