TMB Documentation: atomic::Block< Type > Struct Template Reference
atomic::Block< Type > Struct Template Reference
#include <expm.hpp>
Public Types
typedef Type ScalarType
Public Member Functions
Block ()
Block (matrix< Type > A_)
Block< Type > operator* (Block< Type > other)
Block< Type > scale (Type c)
Block< Type > addIdentity ()
Type norm ()
Block< Type > inverse ()
Block< Type > & operator+= (Block< Type > x)
Block< Type > & operator-= (Block< Type > x)
Public Attributes
matrix< Type > A
Detailed Description
template<class Type>
struct atomic::Block< Type >
Definition at line 7 of file expm.hpp.
Member Typedef Documentation
template<class Type> typedef Type atomic::Block< Type >::ScalarType
Definition at line 8 of file expm.hpp.
Constructor & Destructor Documentation
template<class Type> atomic::Block< Type >::Block () inline
Definition at line 10 of file expm.hpp.
Referenced by atomic::Block< double >::addIdentity(), atomic::Block< double >::inverse(), atomic::Block< double >::operator*(), and atomic::Block< double >::scale().
template<class Type> atomic::Block< Type >::Block (matrix< Type > A_) inline
Definition at line 11 of file expm.hpp.
Member Function Documentation
template<class Type> Block<Type> atomic::Block< Type >::addIdentity () inline
Definition at line 21 of file expm.hpp.
template<class Type> Block<Type> atomic::Block< Type >::inverse () inline
Definition at line 35 of file expm.hpp.
template<class Type> Type atomic::Block< Type >::norm () inline
Definition at line 28 of file expm.hpp.
template<class Type> Block<Type> atomic::Block< Type >::operator* (Block< Type > other) inline
Definition at line 13 of file expm.hpp.
template<class Type> Block<Type>& atomic::Block< Type >::operator+= (Block< Type > x) inline
Definition at line 39 of file expm.hpp.
template<class Type> Block<Type>& atomic::Block< Type >::operator-= (Block< Type > x) inline
Definition at line 40 of file expm.hpp.
template<class Type> Block<Type> atomic::Block< Type >::scale (Type c) inline
Definition at line 17 of file expm.hpp.
Member Data Documentation
template<class Type> matrix<Type> atomic::Block< Type >::A
Definition at line 9 of file expm.hpp.
Referenced by atomic::Block< double >::addIdentity(), atomic::Block< double >::Block(), atomic::Block< double >::inverse(), atomic::Block< double >::norm(), atomic::Block< double >::operator*(), atomic::Block< double >::operator+=(), atomic::Block< double >::operator-=(), and atomic::Block< double >::scale().
The documentation for this struct was generated from the following file:
expm.hpp
License: GPL v2