TMB Documentation: array< Type > Struct Template Reference
array< Type > Struct Template Reference
Array class used by TMB.
#include <array.hpp>
Inherits Map< Array< Type, Dynamic, 1 > >.
Public Types
typedef Array< Type, Dynamic, 1 > Base
typedef Map< Base > MapBase
Public Member Functions
void setdim (vector< int > dim_)
void initZeroArray (vector< int > dim_)
vector< int > c (int n1)
vector< int > c (int n1, int n2)
vector< int > c (int n1, int n2, int n3)
vector< int > c (int n1, int n2, int n3, int n4)
vector< int > c (int n1, int n2, int n3, int n4, int n5)
vector< int > c (int n1, int n2, int n3, int n4, int n5, int n6)
vector< int > c (int n1, int n2, int n3, int n4, int n5, int n6, int n7)
array ()
array (vector< int > dim_)
Construct array from dimension vector and fill with zeros.
array (int n1)
array (int n1, int n2)
array (int n1, int n2, int n3)
array (int n1, int n2, int n3, int n4)
array (int n1, int n2, int n3, int n4, int n5)
array (int n1, int n2, int n3, int n4, int n5, int n6)
array (int n1, int n2, int n3, int n4, int n5, int n6, int n7)
template<class T >
array (T &x, vector< int > dim_)
template<class T >
array (array< T > &x)
array (Type *p, vector< int > dim_)
array & operator= (const array &other)
template<class T >
array< Type > operator= (T y)
void print ()
int cols ()
Number of outer-most dimensions.
int rows ()
Number of inner-most dimensions.
array< Type > col (int i)
Extract sub-array with write access Index i refers to the outer-most (i.e. final) dimension.
Type & operator() (int i1)
Elementwise subsetting 1D array. Also allowed in general to access the underlying vector of n-dim array.
Type & operator() (int i1, int i2)
Elementwise subsetting 2D array.
Type & operator() (int i1, int i2, int i3)
Elementwise subsetting 3D array.
Type & operator() (int i1, int i2, int i3, int i4)
Elementwise subsetting 4D array.
Type & operator() (int i1, int i2, int i3, int i4, int i5)
Elementwise subsetting 5D array.
Type & operator() (int i1, int i2, int i3, int i4, int i5, int i6)
Elementwise subsetting 6D array.
Type & operator() (int i1, int i2, int i3, int i4, int i5, int i6, int i7)
Elementwise subsetting 7D array.
int index (vector< int > tup)
vector< int > tuple (int i)
array< Type > perm (vector< int > p)
Array permutation. Permutes array dimensions corresponding to permutation vector p.
array< Type > transpose ()
Array transpose (Special case of array permutation)
int mod (int i, int n)
array< Type > rotate (int n)
Array rotate (Special case of array permutation)
tmbutils::matrix< Type > matrix ()
Convert TMB array to matrix by keeping the first dimension and collapsing remaining dimensions.
Public Attributes
vector< int > dim
vector< int > mult
Base vectorcopy
Detailed Description
template<class Type>
struct array< Type >
Array class used by TMB.
The TMB array class is implemented as an Eigen Array of dynamic length with a dimension attribute. The implementation closely follows the way arrays work in R. Vectorized operations are inherited from the Eigen library.
Warning
Methods that are not documented here are inherited from the Eigen library and applied on the underlying n-by-1 array. In general this will yield surprising results for 2D specific array methods.
Examples:
matrix_arrays.cpp, multivariate_distributions.cpp, sam.cpp, and sdv_multi_compact.cpp.
Definition at line 22 of file array.hpp.
Member Typedef Documentation
template<class Type> typedef Array<Type,Dynamic,1> array< Type >::Base
Definition at line 24 of file array.hpp.
template<class Type> typedef Map< Base > array< Type >::MapBase
Definition at line 25 of file array.hpp.
Constructor & Destructor Documentation
template<class Type> array< Type >::array () inline
Definition at line 92 of file array.hpp.
Referenced by array< Type >::col(), and array< Type >::operator=().
template<class Type> array< Type >::array (vector< int > dim_) inline
Construct array from dimension vector and fill with zeros.
Definition at line 95 of file array.hpp.
template<class Type> array< Type >::array (int n1) inline
Definition at line 98 of file array.hpp.
template<class Type> array< Type >::array (int n1, int n2) inline
Definition at line 99 of file array.hpp.
template<class Type> array< Type >::array (int n1, int n2, int n3) inline
Definition at line 100 of file array.hpp.
template<class Type> array< Type >::array (int n1, int n2, int n3, int n4) inline
Definition at line 101 of file array.hpp.
template<class Type> array< Type >::array (int n1, int n2, int n3, int n4, int n5) inline
Definition at line 102 of file array.hpp.
template<class Type> array< Type >::array (int n1, int n2, int n3, int n4, int n5, int n6) inline
Definition at line 103 of file array.hpp.
template<class Type> array< Type >::array (int n1, int n2, int n3, int n4, int n5, int n6, int n7) inline
Definition at line 104 of file array.hpp.
template<class Type> template<class T > array< Type >::array (T & x, vector< int > dim_) inline
Definition at line 108 of file array.hpp.
template<class Type> template<class T > array< Type >::array (array< T > & x) inline
Definition at line 116 of file array.hpp.
template<class Type> array< Type >::array (Type * p, vector< int > dim_) inline
Definition at line 124 of file array.hpp.
Member Function Documentation
template<class Type> vector<int> array< Type >::c (int n1) inline
Definition at line 54 of file array.hpp.
Referenced by array< Type >::array(), and array< Type >::operator()().
template<class Type> vector<int> array< Type >::c (int n1, int n2) inline
Definition at line 59 of file array.hpp.
template<class Type> vector<int> array< Type >::c (int n1, int n2, int n3) inline
Definition at line 64 of file array.hpp.
template<class Type> vector<int> array< Type >::c (int n1, int n2, int n3, int n4) inline
Definition at line 69 of file array.hpp.
template<class Type> vector<int> array< Type >::c (int n1, int n2, int n3, int n4, int n5) inline
Definition at line 74 of file array.hpp.
template<class Type> vector<int> array< Type >::c (int n1, int n2, int n3, int n4, int n5, int n6) inline
Definition at line 79 of file array.hpp.
template<class Type> vector<int> array< Type >::c (int n1, int n2, int n3, int n4, int n5, int n6, int n7) inline
Definition at line 84 of file array.hpp.
template<class Type> array<Type> array< Type >::col (int i) inline
Extract sub-array with write access Index i refers to the outer-most (i.e. final) dimension.
Definition at line 188 of file array.hpp.
Referenced by contAR2_t< scalartype_ >::operator()().
template<class Type> int array< Type >::cols () inline
Number of outer-most dimensions.
Returns
Last array dimension (Similar to R's ncol in 2D case only)
Definition at line 174 of file array.hpp.
Referenced by array< Type >::col().
template<class Type> int array< Type >::index (vector< int > tup) inline
Definition at line 232 of file array.hpp.
Referenced by array< Type >::operator()(), and array< Type >::perm().
template<class Type> void array< Type >::initZeroArray (vector< int > dim_) inline
Definition at line 46 of file array.hpp.
Referenced by array< Type >::array(), and array< Type >::operator=().
template<class Type> tmbutils::matrix<Type> array< Type >::matrix () inline
Convert TMB array to matrix by keeping the first dimension and collapsing remaining dimensions.
E.g. if array dimension is (n1,n2,n3) the resulting matrix dimension is (n1, n2*n3).
Definition at line 297 of file array.hpp.
template<class Type> int array< Type >::mod (int i, int n) inline
Definition at line 269 of file array.hpp.
Referenced by array< Type >::rotate().
template<class Type> Type& array< Type >::operator() (int i1) inline
Elementwise subsetting 1D array. Also allowed in general to access the underlying vector of n-dim array.
Definition at line 203 of file array.hpp.
template<class Type> Type& array< Type >::operator() (int i1, int i2) inline
Elementwise subsetting 2D array.
Definition at line 207 of file array.hpp.
template<class Type> Type& array< Type >::operator() (int i1, int i2, int i3) inline
Elementwise subsetting 3D array.
Definition at line 211 of file array.hpp.
template<class Type> Type& array< Type >::operator() (int i1, int i2, int i3, int i4) inline
Elementwise subsetting 4D array.
Definition at line 215 of file array.hpp.
template<class Type> Type& array< Type >::operator() (int i1, int i2, int i3, int i4, int i5) inline
Elementwise subsetting 5D array.
Definition at line 219 of file array.hpp.
template<class Type> Type& array< Type >::operator() (int i1, int i2, int i3, int i4, int i5, int i6) inline
Elementwise subsetting 6D array.
Definition at line 223 of file array.hpp.
template<class Type> Type& array< Type >::operator() (int i1, int i2, int i3, int i4, int i5, int i6, int i7) inline
Elementwise subsetting 7D array.
Definition at line 227 of file array.hpp.
template<class Type> array& array< Type >::operator= (const array< Type > & other) inline
Definition at line 135 of file array.hpp.
template<class Type> template<class T > array<Type> array< Type >::operator= (T y) inline
Definition at line 155 of file array.hpp.
template<class Type> array<Type> array< Type >::perm (vector< int > p) inline
Array permutation. Permutes array dimensions corresponding to permutation vector p.
Definition at line 250 of file array.hpp.
Referenced by array< Type >::rotate(), and array< Type >::transpose().
template<class Type> void array< Type >::print () inline
Definition at line 161 of file array.hpp.
template<class Type> array<Type> array< Type >::rotate (int n) inline
Array rotate (Special case of array permutation)
Rotates array dimension with n steps where n can be any (positive or negative) integer. If e.g. x has dimension [3,4,5,6] then x.rotate(1) has dimension [6,3,4,5].
Definition at line 277 of file array.hpp.
template<class Type> int array< Type >::rows () inline
Number of inner-most dimensions.
Returns
First array dimension (Similar to R's nrow)
Definition at line 181 of file array.hpp.
Referenced by array< Type >::matrix().
template<class Type> void array< Type >::setdim (vector< int > dim_) inline
Definition at line 38 of file array.hpp.
Referenced by array< Type >::array(), array< Type >::initZeroArray(), and array< Type >::operator=().
template<class Type> array<Type> array< Type >::transpose () inline
Array transpose (Special case of array permutation)
If e.g. x has dimension [3,4,5,6] then x.transpose() has dimension [6,5,4,3].
Examples:
sdv_multi_compact.cpp.
Definition at line 263 of file array.hpp.
Referenced by contAR2_t< scalartype_ >::operator()().
template<class Type> vector<int> array< Type >::tuple (int i) inline
Definition at line 237 of file array.hpp.
Referenced by array< Type >::perm().
Member Data Documentation
template<class Type> vector<int> array< Type >::dim
Definition at line 27 of file array.hpp.
Referenced by array< Type >::array(), array< Type >::col(), array< Type >::cols(), array< Type >::index(), array< Type >::operator=(), array< Type >::perm(), array< Type >::print(), array< Type >::rotate(), array< Type >::rows(), array< Type >::setdim(), array< Type >::transpose(), and array< Type >::tuple().
template<class Type> vector<int> array< Type >::mult
Definition at line 34 of file array.hpp.
Referenced by array< Type >::index(), array< Type >::setdim(), and array< Type >::tuple().
template<class Type> Base array< Type >::vectorcopy
Definition at line 36 of file array.hpp.
Referenced by array< Type >::array(), and array< Type >::initZeroArray().
The documentation for this struct was generated from the following file:
array.hpp
License: GPL v2