TMB Documentation: memory_manager_struct Struct Reference
memory_manager_struct Struct Reference
Controls the life span of objects created in the C++ template (jointly R/C++)
#include <tmb_core.hpp>
Public Member Functions
void RegisterCFinalizer (SEXP list)
Register "list" in memory_manager_struct.
void CallCFinalizer (SEXP x)
Revmoves "x" from memory_manager_struct.
void clear ()
memory_manager_struct ()
Public Attributes
int counter
Number of objects alive that "memory_manager_struct" has allocated.
std::map< SEXP_t, SEXP_t > alive
Detailed Description
Controls the life span of objects created in the C++ template (jointly R/C++)
Definition at line 39 of file tmb_core.hpp.
Constructor & Destructor Documentation
memory_manager_struct::memory_manager_struct () inline
Definition at line 61 of file tmb_core.hpp.
Member Function Documentation
void memory_manager_struct::CallCFinalizer (SEXP x) inline
Revmoves "x" from memory_manager_struct.
Definition at line 49 of file tmb_core.hpp.
Referenced by finalize(), finalizeADFun(), finalizeDoubleFun(), and finalizeparallelADFun().
void memory_manager_struct::clear () inline
Definition at line 53 of file tmb_core.hpp.
void memory_manager_struct::RegisterCFinalizer (SEXP list) inline
Register "list" in memory_manager_struct.
Definition at line 43 of file tmb_core.hpp.
Referenced by ptrList().
Member Data Documentation
std::map<SEXP_t,SEXP_t> memory_manager_struct::alive
Definition at line 41 of file tmb_core.hpp.
Referenced by CallCFinalizer(), clear(), and RegisterCFinalizer().
int memory_manager_struct::counter
Number of objects alive that "memory_manager_struct" has allocated.
Definition at line 40 of file tmb_core.hpp.
Referenced by CallCFinalizer(), memory_manager_struct(), and RegisterCFinalizer().
The documentation for this struct was generated from the following file:
tmb_core.hpp
License: GPL v2