TMB Documentation: TMBad::intervals< T > Struct Template Reference
TMBad::intervals< T > Struct Template Reference
Union of closed intervals.
#include <global.hpp>
Public Member Functions
template<class F >
F & apply (F &f) const
Apply a functor to each interval.
bool insert (T a, T b)
Insert new interval [a,b].
Detailed Description
template<class T>
struct TMBad::intervals< T >
Union of closed intervals.
Definition at line 47 of file global.hpp.
Member Function Documentation
insert()
template<class T> bool TMBad::intervals< T >::insert (T a, T b) inline
Insert new interval [a,b].
Returns
false if union did not change. true otherwise.
Definition at line 58 of file global.hpp.
Referenced by TMBad::intervals< Index >::apply(), TMBad::ReverseArgs< Type >::dy_segment(), and TMBad::global::forward_dense().
The documentation for this struct was generated from the following file:
global.hpp
License: GPL v2