TMB Documentation: tmb_core.hpp File Reference
tmb_core.hpp File Reference
Interfaces to R and CppAD.
Classes
struct SEXP_t
TMB: SEXP type.
struct memory_manager_struct
Controls the life span of objects created in the C++ template (jointly R/C++)
struct isDouble< Type >
struct isDouble< double >
struct data_indicator< VT, Type >
struct report_stack< Type >
Used by ADREPORT.
class objective_function< Type >
Type definition of user-provided objective function (i.e. neg. log. like)
struct parallel_accumulator< Type >
Helper to manage parallel accumulation.
Macros
#define TMB_TRY try
#define TMB_CATCH catch(std::bad_alloc& ba)
#define TMB_ERROR_BAD_ALLOC
#define PARAMETER_MATRIX(name) tmbutils::matrix<Type> name(objective_function::fillShape(asMatrix<Type>(objective_function::getShape(#name,&isMatrix)),#name));
Get parameter matrix from R and declare it as matrix<Type>
#define PARAMETER_VECTOR(name) vector<Type> name(objective_function::fillShape(asVector<Type>(objective_function::getShape(#name,&isNumeric)),#name));
Get parameter vector from R and declare it as vector<Type>
#define PARAMETER(name) Type name(objective_function::fillShape(asVector<Type>(objective_function::getShape(#name,&isNumericScalar)),#name)[0]);
Get parameter scalar from R and declare it as Type.
#define DATA_VECTOR(name)
Get data vector from R and declare it as vector<Type>
#define DATA_MATRIX(name)
Get data matrix from R and declare it as matrix<Type>
#define DATA_SCALAR(name)
Get data scalar from R and declare it as Type.
#define DATA_INTEGER(name)
Get data scalar from R and declare it as int.
#define DATA_FACTOR(name)
Get data vector of type "factor" from R and declare it as a zero-based integer vector.
#define DATA_IVECTOR(name)
Get data vector of type "integer" from R and declare it vector<int>. (DATA_INTEGER is for a scalar integer)
#define NLEVELS(name) LENGTH(getAttrib(getListElement(this->data,#name),install("levels")))
Get the number of levels of a data factor from R.
#define DATA_SPARSE_MATRIX(name)
Get sparse matrix from R and declare it as Eigen::SparseMatrix<Type>
#define REPORT(name)
Report scalar, vector or array back to R without derivative information. Important: REPORT(name) must not be used before name has been assigned a value.
#define ADREPORT(name) objective_function::reportvector.push(name,#name);
Report scalar, vector or array back to R with derivative information. The result is retrieved in R via the R function sdreport(). Important: ADREPORT(name) must not be used before name has been assigned a value.
#define PARALLEL_REGION if(this->parallel_region())
#define DATA_ARRAY(name)
Get data array from R and declare it as array<Type>
#define PARAMETER_ARRAY(name) tmbutils::array<Type> name(objective_function::fillShape(tmbutils::asArray<Type>(objective_function::getShape(#name,&isArray)),#name));
Get parameter array from R and declare it as array<Type>
#define DATA_IMATRIX(name)
Get data matrix from R and declare it as matrix<int>
#define DATA_IARRAY(name)
Get data array from R and declare it as array<int>
#define DATA_STRUCT(name, struct) struct<Type> name(getListElement(this->data,#name));
Get data list object from R and makes it available in C++.
#define DATA_ARRAY_INDICATOR(name, obs)
Declare an indicator array 'name' of same shape as 'obs'.
#define DATA_VECTOR_INDICATOR(name, obs)
Declare an indicator vector 'name' of same shape as 'obs'.
#define KEEP_COL(col) (keepcol[col])
#define KEEP_ROW(row, col) (KEEP_COL(row) & (row>=col))
Typedefs
typedef Rboolean(* RObjectTester)(SEXP)
Functions
bool operator< (SEXP_t x, SEXP_t y)
SEXP ptrList (SEXP x)
Convert x to TMB-format for R/C++ communication.
template<class ADFunPointer >
void optimizeTape (ADFunPointer pf)
Call the optimize method of an ADFun object pointer.
void RObjectTestExpectedType (SEXP x, RObjectTester expectedtype, const char *nam)
Rboolean isValidSparseMatrix (SEXP x)
Rboolean isNumericScalar (SEXP x)
template<class Type >
matrix< int > HessianSparsityPattern (ADFun< Type > *pf)
Get the hessian sparsity pattern of ADFun object pointer.
SEXP getListElement (SEXP list, const char *str, RObjectTester expectedtype=NULL)
Get list element named "str", or return NULL.
void Independent (vector< double > x)
Do nothing if we are trying to tape non AD-types.
template<class ADFunType >
SEXP EvalADFunObjectTemplate (SEXP f, SEXP theta, SEXP control)
Evaluates an ADFun object from R.
template<class ADFunType >
void finalize (SEXP x)
Garbage collect an ADFun or parallelADFun object pointer.
ADFun< double > * MakeADFunObject (SEXP data, SEXP parameters, SEXP report, SEXP control, int parallel_region=-1, SEXP &info=R_NilValue)
Construct ADFun object.
void finalizeADFun (SEXP x)
Garbage collect an ADFun object pointer.
void finalizeparallelADFun (SEXP x)
SEXP MakeADFunObject (SEXP data, SEXP parameters, SEXP report, SEXP control)
Construct ADFun object.
SEXP InfoADFunObject (SEXP f)
SEXP optimizeADFunObject (SEXP f)
Call tape optimization function in CppAD.
SEXP getTag (SEXP f)
Get tag of external pointer.
SEXP EvalADFunObject (SEXP f, SEXP theta, SEXP control)
void finalizeDoubleFun (SEXP x)
SEXP MakeDoubleFunObject (SEXP data, SEXP parameters, SEXP report)
SEXP EvalDoubleFunObject (SEXP f, SEXP theta, SEXP control)
SEXP getParameterOrder (SEXP data, SEXP parameters, SEXP report)
Gets parameter order by running the user template.
ADFun< double > * MakeADGradObject (SEXP data, SEXP parameters, SEXP report, int parallel_region=-1)
SEXP MakeADGradObject (SEXP data, SEXP parameters, SEXP report)
Tape the gradient using nested AD types.
sphess MakeADHessObject2 (SEXP data, SEXP parameters, SEXP report, SEXP skip, int parallel_region=-1)
Tape the hessian[cbind(i,j)] using nested AD types.
template<class ADFunType >
SEXP asSEXP (const sphess_t< ADFunType > &H, const char *tag)
Convert sparse matrix H to SEXP format that can be returned to R.
SEXP MakeADHessObject2 (SEXP data, SEXP parameters, SEXP report, SEXP skip)
SEXP usingAtomics ()
SEXP dummy_getParameterOrder (SEXP data, SEXP parameters, SEXP report)
Variables
struct memory_manager_struct memory_manager
bool _openmp =false
Detailed Description
Interfaces to R and CppAD.
Definition in file tmb_core.hpp.
Macro Definition Documentation
#define ADREPORT (name) objective_function::reportvector.push(name,#name);
Report scalar, vector or array back to R with derivative information. The result is retrieved in R via the R function sdreport(). Important: ADREPORT(name) must not be used before name has been assigned a value.
Examples:
ar1_4D.cpp, laplace.cpp, linreg.cpp, longlinreg.cpp, and orange_big.cpp.
Definition at line 236 of file tmb_core.hpp.
#define DATA_ARRAY (name)
Value:
tmbutils::array<Type> name;                                             \
if (!isNull(getListElement(objective_function::parameters,#name))) {    \
  name = objective_function::fillShape(tmbutils::asArray<Type>(         \
         objective_function::getShape(#name,&isArray)),#name);          \
} else {                                                                \
  name = tmbutils::asArray<Type>(getListElement(                        \
         objective_function::data,#name,&isArray));                     \
}
Get data array from R and declare it as array<Type>
Note
If name is found in the parameter list it will be read as a parameter array.
Examples:
mvrw.cpp, mvrw_sparse.cpp, sam.cpp, sdv_multi.cpp, and sdv_multi_compact.cpp.
Definition at line 241 of file tmb_core.hpp.
#define DATA_ARRAY_INDICATOR (name, obs)
Value:
data_indicator<tmbutils::array<Type>, Type > name(obs);                 \
if (!isNull(getListElement(objective_function::parameters,#name))) {    \
  name.fill( objective_function::fillShape(asVector<Type>(              \
             objective_function::getShape(#name,&isNumeric)),#name) );  \
}
Declare an indicator array 'name' of same shape as 'obs'.
Definition at line 314 of file tmb_core.hpp.
#define DATA_FACTOR (name)
Value:
vector<int> name(asVector<int>(\
        getListElement(objective_function::data,#name,&isNumeric)));
Get data vector of type "factor" from R and declare it as a zero-based integer vector.
The following example (R code) shows what you have on the R side and what is being received by the C++ template:
> x=factor(letters[4:10])
> x
[1] d e f g h i j
Levels: d e f g h i j
# The zero-based integer vector that the C++ template sees
> unclass(x) - 1
[1] 0 1 2 3 4 5 6
Examples:
lr_test.cpp, nmix.cpp, orange_big.cpp, and socatt.cpp.
Definition at line 219 of file tmb_core.hpp.
#define DATA_IARRAY (name)
Value:
tmbutils::array<int> name(tmbutils::asArray<int>(\
        getListElement(objective_function::data,#name,&isArray)));
Get data array from R and declare it as array<int>
Examples:
sam.cpp.
Definition at line 256 of file tmb_core.hpp.
#define DATA_IMATRIX (name)
Value:
matrix<int> name(asMatrix<int>(\
        getListElement(objective_function::data,#name,&isMatrix)));
Get data matrix from R and declare it as matrix<int>
Definition at line 253 of file tmb_core.hpp.
#define DATA_INTEGER (name)
Value:
int name(CppAD::Integer(asVector<Type>(\
        getListElement(objective_function::data,#name,&isNumericScalar))[0]));
Get data scalar from R and declare it as int.
Examples:
laplace.cpp, matrix_arrays.cpp, nmix.cpp, orange_big.cpp, sam.cpp, sdv_multi.cpp, sdv_multi_compact.cpp, socatt.cpp, and spatial.cpp.
Definition at line 202 of file tmb_core.hpp.
#define DATA_IVECTOR (name)
Value:
vector<int> name(asVector<int>(\
        getListElement(objective_function::data,#name,&isNumeric)));
Get data vector of type "integer" from R and declare it vector<int>. (DATA_INTEGER is for a scalar integer)
Examples:
spde.cpp, and spde_aniso.cpp.
Definition at line 222 of file tmb_core.hpp.
#define DATA_MATRIX (name)
Value:
matrix<Type> name(asMatrix<Type>(\
        getListElement(objective_function::data,#name,&isMatrix)));
Get data matrix from R and declare it as matrix<Type>
Examples:
laplace.cpp, nmix.cpp, socatt.cpp, spatial.cpp, spde.cpp, and spde_aniso.cpp.
Definition at line 196 of file tmb_core.hpp.
#define DATA_SCALAR (name)
Value:
Type name(asVector<Type>(\
        getListElement(objective_function::data,#name,&isNumericScalar))[0]);
Get data scalar from R and declare it as Type.
Examples:
nan_error_ex.cpp.
Definition at line 199 of file tmb_core.hpp.
#define DATA_SPARSE_MATRIX (name)
Value:
Eigen::SparseMatrix<Type> name(tmbutils::asSparseMatrix<Type>(\
        getListElement(objective_function::data,#name,&isValidSparseMatrix)));
Get sparse matrix from R and declare it as Eigen::SparseMatrix<Type>
Definition at line 227 of file tmb_core.hpp.
#define DATA_STRUCT (name, struct) struct<Type> name(getListElement(this->data,#name));
Get data list object from R and makes it available in C++.
Example (incomplete) of use: In R:
data <- list()
data$object <- list(a=1:10, b=matrix(1:6,2))
obj <- MakeADFun(data,........)
In C++:
// Corresponding list object on the C++ side
template<class Type>
struct my_list {
  vector<Type> a;
  matrix<Type> b;
  my_list(SEXP x){ // Constructor
    a = asVector<Type>(getListElement(x,"a"));
    b = asMatrix<Type>(getListElement(x,"b"));
  }
};
template<class Type>
Type objective_function<Type>::operator() ()
{
  DATA_STRUCT(object, my_list);
  REPORT(object.a); // Now you can use "a" and "b" as you like
  REPORT(object.b);
  return 0;
}
Examples:
spde.cpp, and spde_aniso.cpp.
Definition at line 291 of file tmb_core.hpp.
#define DATA_VECTOR (name)
Value:
vector<Type> name;                                                      \
if (!isNull(getListElement(objective_function::parameters,#name))) {    \
  name = objective_function::fillShape(asVector<Type>(                  \
         objective_function::getShape(#name,&isNumeric)),#name);        \
} else {                                                                \
  name = asVector<Type>(getListElement(                                 \
         objective_function::data,#name,&isNumeric));                   \
}
Get data vector from R and declare it as vector<Type>
Note
If name is found in the parameter list it will be read as a parameter vector.
Examples:
ar1_4D.cpp, laplace.cpp, linreg.cpp, linreg_parallel.cpp, longlinreg.cpp, lr_test.cpp, nmix.cpp, orange_big.cpp, sam.cpp, sde_linear.cpp, spatial.cpp, spde.cpp, spde_aniso.cpp, thetalog.cpp, and transform.cpp.
Definition at line 186 of file tmb_core.hpp.
#define DATA_VECTOR_INDICATOR (name, obs)
Value:
data_indicator<tmbutils::vector<Type>, Type > name(obs);                \
if (!isNull(getListElement(objective_function::parameters,#name))) {    \
  name.fill( objective_function::fillShape(asVector<Type>(              \
             objective_function::getShape(#name,&isNumeric)),#name) );  \
}
Declare an indicator vector 'name' of same shape as 'obs'.
Definition at line 323 of file tmb_core.hpp.
#define KEEP_COL (col) (keepcol[col])
Referenced by MakeADHessObject2().
#define KEEP_ROW (row, col) (KEEP_COL(row) & (row>=col))
Referenced by MakeADHessObject2().
#define NLEVELS (name) LENGTH(getAttrib(getListElement(this->data,#name),install("levels")))
Get the number of levels of a data factor from R.
Definition at line 225 of file tmb_core.hpp.
#define PARALLEL_REGION if(this->parallel_region())
Definition at line 237 of file tmb_core.hpp.
#define PARAMETER (name) Type name(objective_function::fillShape(asVector<Type>(objective_function::getShape(#name,&isNumericScalar)),#name)[0]);
Get parameter scalar from R and declare it as Type.
Examples:
ar1_4D.cpp, laplace.cpp, linreg.cpp, linreg_parallel.cpp, longlinreg.cpp, matrix_arrays.cpp, multivariate_distributions.cpp, mvrw.cpp, mvrw_sparse.cpp, nan_error_ex.cpp, nmix.cpp, orange_big.cpp, sam.cpp, sde_linear.cpp, socatt.cpp, spatial.cpp, spde.cpp, spde_aniso.cpp, thetalog.cpp, and transform.cpp.
Definition at line 182 of file tmb_core.hpp.
#define PARAMETER_ARRAY (name) tmbutils::array<Type> name(objective_function::fillShape(tmbutils::asArray<Type>(objective_function::getShape(#name,&isArray)),#name));
Get parameter array from R and declare it as array<Type>
Examples:
ar1_4D.cpp, mvrw.cpp, mvrw_sparse.cpp, sam.cpp, sdv_multi.cpp, and sdv_multi_compact.cpp.
Definition at line 251 of file tmb_core.hpp.
#define PARAMETER_MATRIX (name) tmbutils::matrix<Type> name(objective_function::fillShape(asMatrix<Type>(objective_function::getShape(#name,&isMatrix)),#name));
Get parameter matrix from R and declare it as matrix<Type>
Definition at line 178 of file tmb_core.hpp.
#define PARAMETER_VECTOR (name) vector<Type> name(objective_function::fillShape(asVector<Type>(objective_function::getShape(#name,&isNumeric)),#name));
Get parameter vector from R and declare it as vector<Type>
Examples:
laplace.cpp, lr_test.cpp, mvrw.cpp, mvrw_sparse.cpp, nmix.cpp, orange_big.cpp, sam.cpp, sde_linear.cpp, sdv_multi.cpp, sdv_multi_compact.cpp, socatt.cpp, spatial.cpp, spde.cpp, spde_aniso.cpp, thetalog.cpp, and transform.cpp.
Definition at line 180 of file tmb_core.hpp.
#define REPORT (name)
Value:
if(isDouble<Type>::value && this->current_parallel_region<0){          \
                        defineVar(install(#name),asSEXP(name),objective_function::report);}
Report scalar, vector or array back to R without derivative information. Important: REPORT(name) must not be used before name has been assigned a value.
Examples:
multivariate_distributions.cpp, and spde_aniso.cpp.
Definition at line 231 of file tmb_core.hpp.
#define TMB_CATCH catch(std::bad_alloc& ba)
Definition at line 20 of file tmb_core.hpp.
Referenced by EvalADFunObject(), EvalDoubleFunObject(), getParameterOrder(), MakeADFunObject(), MakeADGradObject(), MakeADHessObject2(), and MakeDoubleFunObject().
#define TMB_ERROR_BAD_ALLOC
Value:
error("Memory allocation fail in function '%s'\n", \
                                  __FUNCTION__)
Definition at line 21 of file tmb_core.hpp.
Referenced by EvalADFunObject(), EvalDoubleFunObject(), getParameterOrder(), MakeADFunObject(), MakeADGradObject(), MakeADHessObject2(), and MakeDoubleFunObject().
#define TMB_TRY try
Definition at line 19 of file tmb_core.hpp.
Referenced by EvalADFunObject(), EvalDoubleFunObject(), getParameterOrder(), MakeADFunObject(), MakeADGradObject(), MakeADHessObject2(), and MakeDoubleFunObject().
Typedef Documentation
typedef Rboolean(* RObjectTester)(SEXP)
Definition at line 152 of file tmb_core.hpp.
Function Documentation
template<class ADFunType > SEXP asSEXP (const sphess_t< ADFunType > & H, const char * tag)
Convert sparse matrix H to SEXP format that can be returned to R.
Definition at line 1325 of file tmb_core.hpp.
Referenced by EvalADFunObjectTemplate(), EvalDoubleFunObject(), InfoADFunObject(), and MakeADHessObject2().
SEXP dummy_getParameterOrder (SEXP data, SEXP parameters, SEXP report)
Definition at line 1437 of file tmb_core.hpp.
SEXP EvalADFunObject (SEXP f, SEXP theta, SEXP control)
Examples:
called_from_R.cpp.
Definition at line 1035 of file tmb_core.hpp.
template<class ADFunType > SEXP EvalADFunObjectTemplate (SEXP f, SEXP theta, SEXP control)
Evaluates an ADFun object from R.
Template argument can be "ADFun" or an object extending "ADFun" such as "parallelADFun".
Parameters
f R external pointer to ADFunType
theta R vector of parameters
control R list controlling what to be returned
It is assumed that where n and m are found from f. The list "control" can contain the following components:
order: mandatory integer 0,1,2, or 3 with order of derivatives to be calculated.
hessiancols, hessianrows: Optional one-based integer vectors of the same length. Used only in the case where order=2 to extract specific entries of hessian.
sparsitypattern: Integer flag. Return sparsity pattern instead of numerical values?
rangeweight: Optional R vector of doubles of length m. If supplied, a 1st order reverse mode sweep is performed in this range direction.
rangecomponent: Optional one-based integer (scalar) between 1 and m. Used to select a given component of the vector f(x). dumpstack: Integer flag. If non zero the entire operation stack is dumped as text output during 0-order forward sweep.
Possible output depends on "order".
order==0: Calculate f(x) output as vector of length m.
order==1: If "rangeweight" is supplied, calculate the gradient of the function x -> inner_prod(f(x),w) from R^n->R. Otherwise, calculate the full jacobian (of dimension m*n).
order==2: If nothing further is specified, calculate the full hessian of the function x->f(x)[rangecomponent] from R^n->R
All other usage is considered deprecated/experimental and may be removed in the future.
Definition at line 765 of file tmb_core.hpp.
Referenced by EvalADFunObject().
SEXP EvalDoubleFunObject (SEXP f, SEXP theta, SEXP control)
Examples:
called_from_R.cpp.
Definition at line 1092 of file tmb_core.hpp.
template<class ADFunType > void finalize (SEXP x)
Garbage collect an ADFun or parallelADFun object pointer.
Definition at line 862 of file tmb_core.hpp.
void finalizeADFun (SEXP x)
Garbage collect an ADFun object pointer.
Definition at line 902 of file tmb_core.hpp.
Referenced by MakeADFunObject(), and MakeADGradObject().
void finalizeDoubleFun (SEXP x)
Definition at line 1058 of file tmb_core.hpp.
Referenced by MakeDoubleFunObject().
void finalizeparallelADFun (SEXP x)
Definition at line 908 of file tmb_core.hpp.
Referenced by MakeADFunObject(), and MakeADGradObject().
SEXP getListElement (SEXP list, const char * str, RObjectTester expectedtype = NULL)
Get list element named "str", or return NULL.
Definition at line 349 of file tmb_core.hpp.
Referenced by EvalADFunObjectTemplate(), objective_function< Type >::fillmap(), objective_function< Type >::fillShape(), objective_function< Type >::getShape(), MakeADFunObject(), R_inla::spde_aniso_t< Type >::spde_aniso_t(), and R_inla::spde_t< Type >::spde_t().
SEXP getParameterOrder (SEXP data, SEXP parameters, SEXP report)
Gets parameter order by running the user template.
We spend a function evaluation on getting the parameter order (!)
Examples:
called_from_R.cpp.
Definition at line 1121 of file tmb_core.hpp.
Referenced by dummy_getParameterOrder().
SEXP getTag (SEXP f)
Get tag of external pointer.
Definition at line 1031 of file tmb_core.hpp.
template<class Type > matrix<int> HessianSparsityPattern (ADFun< Type > * pf)
Get the hessian sparsity pattern of ADFun object pointer.
Definition at line 333 of file tmb_core.hpp.
Referenced by EvalADFunObjectTemplate().
void Independent (vector< double > x)
Do nothing if we are trying to tape non AD-types.
Definition at line 368 of file tmb_core.hpp.
Referenced by atomic::forrev(), atomic::generate_tape(), MakeADFunObject(), MakeADGradObject(), MakeADHessObject2(), autodiff::gradient_t< Functor, Type >::operator()(), autodiff::hessian_t< Functor, Type >::operator()(), and autodiff::jacobian_t< Functor, Type >::operator()().
SEXP InfoADFunObject (SEXP f)
Examples:
called_from_R.cpp.
Definition at line 993 of file tmb_core.hpp.
Rboolean isNumericScalar (SEXP x)
Definition at line 167 of file tmb_core.hpp.
Rboolean isValidSparseMatrix (SEXP x)
Definition at line 163 of file tmb_core.hpp.
ADFun<double>* MakeADFunObject (SEXP data, SEXP parameters, SEXP report, SEXP control, int parallel_region = -1, SEXP & info = R_NilValue)
Construct ADFun object.
Examples:
called_from_R.cpp.
Definition at line 871 of file tmb_core.hpp.
Referenced by MakeADFunObject().
SEXP MakeADFunObject (SEXP data, SEXP parameters, SEXP report, SEXP control)
Construct ADFun object.
Definition at line 916 of file tmb_core.hpp.
ADFun< double >* MakeADGradObject (SEXP data, SEXP parameters, SEXP report, int parallel_region = -1)
Examples:
called_from_R.cpp.
Definition at line 1140 of file tmb_core.hpp.
Referenced by MakeADGradObject().
SEXP MakeADGradObject (SEXP data, SEXP parameters, SEXP report)
Tape the gradient using nested AD types.
Definition at line 1164 of file tmb_core.hpp.
sphess MakeADHessObject2 (SEXP data, SEXP parameters, SEXP report, SEXP skip, int parallel_region = -1)
Tape the hessian[cbind(i,j)] using nested AD types.
skip: integer vector of columns to skip from the hessian (will not change dimension - only treat h[:,skip] and h[skip,:] as zero). Negative subscripts are not allowed.
Examples:
called_from_R.cpp.
Definition at line 1239 of file tmb_core.hpp.
Referenced by MakeADHessObject2().
SEXP MakeADHessObject2 (SEXP data, SEXP parameters, SEXP report, SEXP skip)
Definition at line 1382 of file tmb_core.hpp.
SEXP MakeDoubleFunObject (SEXP data, SEXP parameters, SEXP report)
Examples:
called_from_R.cpp.
Definition at line 1065 of file tmb_core.hpp.
bool operator< (SEXP_t x, SEXP_t y)
Definition at line 37 of file tmb_core.hpp.
SEXP optimizeADFunObject (SEXP f)
Call tape optimization function in CppAD.
Examples:
called_from_R.cpp.
Definition at line 1014 of file tmb_core.hpp.
template<class ADFunPointer > void optimizeTape (ADFunPointer pf)
Call the optimize method of an ADFun object pointer.
Definition at line 114 of file tmb_core.hpp.
Referenced by MakeADHessObject2().
SEXP ptrList (SEXP x)
Convert x to TMB-format for R/C++ communication.
All external pointers returned from TMB should be placed in a list container of length one. Additional information should be set as attributes to the pointer. The memory_manager_struct above knows how to look up the list container given the external pointer. By setting the list element to NULL the memory_manager can trigger the garbage collector (and thereby the finalizers) when the library is unloaded.
Definition at line 76 of file tmb_core.hpp.
Referenced by asSEXP(), MakeADFunObject(), MakeADGradObject(), and MakeDoubleFunObject().
void RObjectTestExpectedType (SEXP x, RObjectTester expectedtype, const char * nam)
Definition at line 153 of file tmb_core.hpp.
Referenced by getListElement(), and objective_function< Type >::getShape().
SEXP usingAtomics ()
Definition at line 1402 of file tmb_core.hpp.
Variable Documentation
bool _openmp =false
Definition at line 109 of file tmb_core.hpp.
struct memory_manager_struct memory_manager
Referenced by finalize(), finalizeADFun(), finalizeDoubleFun(), finalizeparallelADFun(), and ptrList().
License: GPL v2