library(TMB)
compile("linreg.cpp","-O0 -g")
dyn.load(dynlib("linreg"))
set.seed(123)
data <- list(Y=rnorm(10)+1:10,x=1:10)
parameters <- list(a=0,b=0,logSigma=0)
obj <- MakeADFun(data,parameters)
obj$fn()
obj$gr()
