#ifndef _WIN32
#ifndef HAVE_COMPILE_HPP
#define HAVE_COMPILE_HPP
// Autogenerated - do not edit by hand !
#include <dlfcn.h>
#include <stdlib.h>

#include "code_generator.hpp"
#include "global.hpp"

namespace TMBad {

void compile(global &glob, code_config cfg = code_config());
}
#endif  // HAVE_COMPILE_HPP
#endif
