#ifndef HAVE_EIGEN_NUMTRAITS_HPP
#define HAVE_EIGEN_NUMTRAITS_HPP
// Autogenerated - do not edit by hand !
#include <Eigen/Core>

#include "global.hpp"

namespace Eigen {

template <>
struct NumTraits<TMBad::ad_aug> : NumTraits<TMBad::Scalar> {
  typedef TMBad::ad_aug Real;
  typedef TMBad::ad_aug NonInteger;
  typedef TMBad::ad_aug Nested;
  enum {

    IsComplex = 0,

    IsInteger = 0,

    IsSigned = 1,

    RequireInitialization = 1,

    ReadCost = 1,
    AddCost = 2,
    MulCost = 2
  };
};

template <>
struct NumTraits<TMBad::ad_adapt> : NumTraits<TMBad::Scalar> {
  typedef TMBad::ad_adapt Real;
  typedef TMBad::ad_adapt NonInteger;
  typedef TMBad::ad_adapt Nested;
  enum {

    IsComplex = 0,

    IsInteger = 0,

    IsSigned = 1,

    RequireInitialization = 1,

    ReadCost = 1,
    AddCost = 2,
    MulCost = 2
  };
};

template <typename BinOp>
struct ScalarBinaryOpTraits<TMBad::ad_aug, TMBad::Scalar, BinOp> {
  typedef TMBad::ad_aug ReturnType;
};
template <typename BinOp>
struct ScalarBinaryOpTraits<TMBad::Scalar, TMBad::ad_aug, BinOp> {
  typedef TMBad::ad_aug ReturnType;
};

}  // namespace Eigen
#endif  // HAVE_EIGEN_NUMTRAITS_HPP
