#ifndef HAVE_GRAPH2DOT_HPP
#define HAVE_GRAPH2DOT_HPP
// Autogenerated - do not edit by hand !
#include <fstream>
#include <iostream>

#include "global.hpp"

namespace TMBad {

void graph2dot(global glob, graph G, bool show_id = false,
               std::ostream& cout = Rcout);

void graph2dot(global glob, bool show_id = false, std::ostream& cout = Rcout);

void graph2dot(const char* filename, global glob, graph G,
               bool show_id = false);

void graph2dot(const char* filename, global glob, bool show_id = false);

}  // namespace TMBad
#endif  // HAVE_GRAPH2DOT_HPP
