#ifndef HAVE_TMBAD_ALLOW_COMPARISON_HPP
#define HAVE_TMBAD_ALLOW_COMPARISON_HPP
// Autogenerated - do not edit by hand !
#include "global.hpp"

namespace TMBad {
/** \brief Allow / disallow comparison operators for `ad_aug`
    \details It is recommended to disable comparison for the
    non-retaping type `ad_aug`, i.e. not including this file!
*/

bool operator<(const ad_aug &x, const ad_aug &y);
bool operator<(const Scalar &x, const ad_aug &y);
bool operator<=(const ad_aug &x, const ad_aug &y);
bool operator<=(const Scalar &x, const ad_aug &y);
bool operator>(const ad_aug &x, const ad_aug &y);
bool operator>(const Scalar &x, const ad_aug &y);
bool operator>=(const ad_aug &x, const ad_aug &y);
bool operator>=(const Scalar &x, const ad_aug &y);
bool operator==(const ad_aug &x, const ad_aug &y);
bool operator==(const Scalar &x, const ad_aug &y);
bool operator!=(const ad_aug &x, const ad_aug &y);
bool operator!=(const Scalar &x, const ad_aug &y);

}  // namespace TMBad
#endif  // HAVE_TMBAD_ALLOW_COMPARISON_HPP
